# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  web:
    image: nutellaj/cartoonify-web
    depends_on: 
      - mongo
    ports: 
      - '5000:5000'
    volumes: 
      - .:/opt/cartoonify-web